// <auto-generated />
namespace MyDataRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class student_fromOutOfState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(student_fromOutOfState));
        
        string IMigrationMetadata.Id
        {
            get { return "202101221536158_student_fromOutOfState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
