// <auto-generated />
namespace MyDataWithEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class base_entity_student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(base_entity_student));
        
        string IMigrationMetadata.Id
        {
            get { return "202102040149391_base_entity_student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
