// <auto-generated />
namespace MyDataWithEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class address_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(address_key));
        
        string IMigrationMetadata.Id
        {
            get { return "202102041619357_address_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
