// <auto-generated />
namespace MyDataWithEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class address_base_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(address_base_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202102040203417_address_base_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
